//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppCultuEspai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristiquesSales
    {
        public int CaracteristicaID { get; set; }
        public Nullable<int> SalaID { get; set; }
        public string CaracteristicaNom { get; set; }
        public string CaracteristicaValor { get; set; }
        public Nullable<System.DateTime> DataModificacio { get; set; }
    
        public virtual Sales Sales { get; set; }
    }
}
