//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppCultuEspai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esdeveniments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esdeveniments()
        {
            this.Entrades = new HashSet<Entrades>();
            this.Xats = new HashSet<Xats>();
        }
    
        public int EsdevenimentID { get; set; }
        public string Nom { get; set; }
        public string Descripcio { get; set; }
        public Nullable<int> SalaID { get; set; }
        public Nullable<System.DateTime> DataInici { get; set; }
        public Nullable<System.DateTime> DataFi { get; set; }
        public Nullable<int> Aforament { get; set; }
        public Nullable<int> OrganitzadorID { get; set; }
        public string Estat { get; set; }
        public bool DePagament { get; set; }
        public Nullable<int> Preu { get; set; }
        public Nullable<int> EntradesDisp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrades> Entrades { get; set; }
        public virtual Usuaris Usuaris { get; set; }
        public virtual Sales Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xats> Xats { get; set; }
    }
}
