//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppCultuEspai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.CaracteristiquesSales = new HashSet<CaracteristiquesSales>();
            this.Esdeveniments = new HashSet<Esdeveniments>();
        }
    
        public int SalaID { get; set; }
        public string Nom { get; set; }
        public int MetresQuadrats { get; set; }
        public Nullable<int> Aforament { get; set; }
        public bool CadiresFixes { get; set; }
        public string Descripcio { get; set; }
        public string ButacaMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristiquesSales> CaracteristiquesSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esdeveniments> Esdeveniments { get; set; }
    }
}
