//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppCultuEspai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xats
    {
        public int XatID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IDEsdeveniment { get; set; }
        public bool Enviat { get; set; }
    
        public virtual Esdeveniments Esdeveniments { get; set; }
        public virtual Usuaris Usuaris { get; set; }
    }
}
